### PR TITLE
Implement wrapper around LruMap from twitter utils

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by cb372** [comment]
Looks great. Thanks!

I'll release a snapshot in case you want to use this soon, and I'll try to make a proper release later this week.

**Comment by cb372** [comment]
Published 0.6.2-SNAPSHOT to https://oss.sonatype.org/content/repositories/snapshots

**Comment by cb372** [comment]
Never mind, I decided to go ahead and publish 0.6.2 anyway. Should hit Maven Central soon.

**Comment by catap** [comment]
Thanks so much!

**Pull request merged**
