### PR TITLE
update/cats effect 3.0.1

### PR DESCRIPTION
**Pull request by kubukoz**
Supersedes #506.

### CODE REVIEW

**Comment by kubukoz** [comment]
@lewisjkl please take a look ;)

**Comment by kubukoz** [comment]
ummmmm I have no idea why this was skipped/cancelled :|

**Review by lewisjkl — APPROVED** [review]
Looks great, thanks for taking the time to do this! Last month got crazy for me, but I'm hoping to put in the work to get 1.0.0 released soon..

**Comment by kubukoz** [comment]
@lewisjkl WDYT about a milestone with this? :)

**Pull request merged**
