### PR TITLE
Added basic cache stats

### PR DESCRIPTION
**Pull request by perotom**
Would be great to have basic stats for caches. Especially helpful for tests which want to verify if data was retrieved from the cache or not.

TODO: Add documentation

### CODE REVIEW

**Comment by guizmaii** [comment]
IMO, a better idea is just to make the `underlying` cache accessible. This `stats` operation is not something share between all cache implementations. Scalacache is abstraction of common cache operations and should not address specific use cases like this one.

**Comment by perotom** [comment]
Also no problem. Is it possible to make the underlying cache accessible in the next release? Heavily depend on it for testing

**Comment by cb372** [comment]
I agree, just turning the `underlying` parameter in the `CaffeineCache` constructor into a `val` is probably a simpler solution. I don't see any problem with doing that.

**Comment by lewisjkl** [comment]
Looks like this has been resolved and then left alone for quite some time. I am going to close, but we can reopen if anyone desires.

**Pull request closed without merging**
