### PR TITLE
#148 Microsite

### LINKED ISSUE #148: Microsite
Use sbt-microsites to make a website.

The readme is now checked with `tut` so it shouldn't be too much effort to port it over.

Ideally the site would split the documentation into sensible categories, so it's easier to read through than the giant README we currently have.

### PR DESCRIPTION
**Pull request by jan0sch**
This enables the usage of sbt-microsites for generating and publishing
the documentation.

### Changes

* prepare travis-ci for sbt-microsites
* enable publishing via travis-ci
* include sbt-microsite plugin
* add ENSIME files to `.gitignore`
* update sbt to 1.0.4
* create minimal README for main project
* split up old README into multiple files to create the docs from
* some adjustments and refinements
* fixes #148

### CODE REVIEW

**Comment by cb372** [comment]
This is amazing! Thank you for dedicating your weekend to it. 

I'll merge it and push the site manually for now, then set up automation with Travis later. I'll also need to tweak the silly `sed` wrapper in `build.sbt` that updates the version numbers in the readme.

**Comment by cb372** [comment]
OK, something really weird happened when I tried to publish the site. It looks like sbt-ghpages sent the commit to a completely different repo! It created an empty commit on master in one of my private repos. Scary. 

I'll try and sort this out tomorrow.

**Comment by jan0sch** [comment]
Maybe publishing via travis could be used. I prepared this in the `build.sbt` according to the docs: https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html#publish-using-github4s

**Comment by cb372** [comment]
It works! http://cb372.github.io/scalacache/ 🎉 

`rm -r ~/.sbt/ghpages/` fixed the weird behaviour I was seeing last night.

I'll switch back to github4s and set up Travis later.

**Pull request merged**
