### PR TITLE
[WIP] Dependency updates:

### PR DESCRIPTION
**Pull request by golem131**
- update to sbt 1.0.3
- caffeine 2.5.6 -> 2.6.0
- scalajs - 0.6.20 -> 0.6.21
- sclafmt-coursier 1.12 -> 1.14
- reformat scala code
- update cats-effect to 0.5
- update circe 0.8.0 -> 0.9.0-M2
- update scalacheck 1.13.4 -> 1.13.5

### CODE REVIEW

**Comment by cb372** [comment]
Looks like I've introduced some [flaky tests](https://travis-ci.org/cb372/scalacache/jobs/301329957#L1259-L1265) recently. Sorry about that. I'll make an issue for it.

**Comment by golem131** [comment]
#152 affected

**Comment by golem131** [comment]
@cb372 i updated this PR, pls, check, is that FIX for flaky test correct?

**Comment by cb372** [comment]
Yes, that looks fine to me. Thanks for fixing it!

**Pull request merged**
