### PR TITLE
upgrade jedis to 3.7.0

### PR DESCRIPTION
**Pull request by mayman**
Should address #360

### CODE REVIEW

**Comment by mayman** [comment]
@kubukoz would you be able to have a look at this please? 

The upgrade to Jedis 3.7.0 allows the usage of SSL for redis, which is missing from the current implementation of jedis

**Review by kubukoz — APPROVED** [review]

**Comment by kubukoz** [comment]
some compilation failures on 2.12 😅

**Comment by mayman** [comment]
@kubukoz looks like I was missing some type info 🤦, I made sure to run the +test this time!

**Comment by kubukoz** [comment]
Thanks @mayman :)

A snapshot should be released automatically to Sonatype in this job: https://github.com/cb372/scalacache/runs/3665273459?check_suite_focus=true
but I think we'll have a milestone release once we fix #522 (feel free to give it a shot if you want - info in comments on that issue). I think the current milestone is _less_ broken than the main branch so would like to avoid milestoning it.

cc @lewisjkl

**Pull request merged**
